### ISSUE TITLE
1.12 fps hit

### ISSUE THREAD

**Issue by Zygus42** [Exidex/SwingThroughGrass#1]
swingthroughgrass-1.12-1.2.0
forge-1.12-14.21.1.2428-installer-win

Standing in a newly created vanilla world with no other mods and doing nothing costs more than 100fps compared to not having your mod on. I'm guessing that there's something you're checking for too often.

**Comment by Exidex** [comment]
All I am doing in the mod is running some code on LeftClick event, so in general, mod does its things only when you left click on block. There is nothing that could cause this kind of fps drop.
