### ISSUE TITLE
[1.15.2] Doesn't seem to be working.

### ISSUE THREAD

**Issue by mjlmjl888** [Exidex/SwingThroughGrass#10]
I tested it by using an iron sword on the grass and the sword still breaks the grass.

**Comment by Exidex** [comment]
The grass will break in any case whether you hit a mob or not

**Comment by mjlmjl888** [comment]
So you have to hit a mob or you still break grass?

**Comment by Exidex** [comment]
Destroying grass is vanilla behavior and it always happens when you hit it. The mod makes it that when you hit a grass AND there's a mob behind the grass you also hit the mob

**Comment by mjlmjl888** [comment]
Oh okay.
