### ISSUE TITLE
[1.16.1] Error Loading Mods, occurred during loading.

### ISSUE THREAD

**Issue by Gbergz** [Exidex/SwingThroughGrass#11]
Title^

### Screenshot
![image](https://user-images.githubusercontent.com/26634554/90154264-343f2400-dd8a-11ea-917d-6d438bc78295.png)

**Minecraft:** 1.16.1
**Forge:** 32.0.106/107/108
**Mod Version:** [1.5.0](https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass/files/3030485)

**Logs:**
https://hastebin.com/tutaxoduxa.sql

Any ideas?

**-** Gbergz

**Comment by Exidex** [comment]
I probably just messed up language provider requirement. I'll have a look

**Comment by Exidex** [comment]
Just a typo. Fixed in ded6e18. New version is waiting for approval on CurseForge
