### ISSUE TITLE
[1.15.2] Not a only server-side mod

### ISSUE THREAD

**Issue by Intezium** [Exidex/SwingThroughGrass#12]
Forge-31.2.41
SwingThroughGrass-1.4.0
Only Visual
![image](https://user-images.githubusercontent.com/20191322/94384652-c8ebbe80-014b-11eb-967c-4388b17f0691.png)

**Comment by Exidex** [comment]
Fixed in 874f62fbc8e60e7d6041f82b474172f7f9270b4c. For `1.15.2` get version `1.15.2-1.4.1` once it will be approved
