### ISSUE TITLE
[Question] Future Releases?

### ISSUE THREAD

**Issue by Darkosto** [Exidex/SwingThroughGrass#16]
Hey Exidex!

Just wondering if you planned on doing a 1.18 release in the future? Thanks so much for all you're hard work!

Darkosto

**Comment by Exidex** [comment]
@Darkosto Yep, after talking to you I was planning on doing it this weekend.

**Comment by Mrbysco** [comment]
If you need any help I've basically done the work for you on my [Fork](https://github.com/Mrbysco/SwingThroughGrass/) 
(see the [mc1.17.1](https://github.com/Mrbysco/SwingThroughGrass/tree/mc.1.17.1) branch (based on mc.1.16) and [mc.1.18](https://github.com/Mrbysco/SwingThroughGrass/tree/mc.1.18) branch (based on mc.1.17.1))

Bysco

**Comment by Exidex** [comment]
@Darkosto the 1.18 and 1.17.1 (just in case) versions are up on CurseForge.
