### ISSUE TITLE
1.18.2 Request

### ISSUE THREAD

**Issue by CDAGaming** [Exidex/SwingThroughGrass#17]
As the title says, just wondering if a release could be pushed or tagged?

**Comment by BakeJake** [comment]
@CDAGaming,  I have merged and pushed an update to the owner. for now, here is the Jar built from said commit!
Pull Request: https://github.com/Exidex/SwingThroughGrass/pull/19
Mod (swingthroughgrass-1.18.2-1.8.1.jar): https://bit.ly/3HZ9xC5 (Link was crazy long, hosted on my onedrive)

**Comment by Exidex** [comment]
1.18.2 is up on CurseForge. Thanks for the help
