### ISSUE TITLE
[1.12] Mod Interaction w/ SwingThroughGrass

### ISSUE THREAD

**Issue by SnowShock35** [Exidex/SwingThroughGrass#4]
Hi,

This bug is to both @p455w0rd and @Exidex as the issue occurs when only both your mods are present on the client when connecting to a dedicated server .

#### Issue Details

* Minecraft 1.12.2
* Minecraft Forge 14.23.1.2555
* CodeChicken Lib 1.8+ 3.1.3.313
* p455w0rd's Library 2.0.24
* /dank/null 1.0.14
* SwingThroughGrass 1.2.1

#### Issue Description

When connecting to a dedicated server for the first time,  the player will be unable to break tall grass and other decorative plant life blocks. Not only this, the player has an increased destroy speed when attempting to break the plant. No obvious solution presents itself - even re-logging and when the server restarts the same behaviour occurs once more. Just after a certain time (which is random from what I can tell.) the issue no longer occurs and everything is fine once more. Also, it's worth noting that this is **not** spawn protection causing the issue. 

I have little to add to this, on what can only be described as a rather peculiar, issue.

#### Issue Media

latest.log - client
https://pastebin.com/DpYstaPZ

latest.log - server
https://pastebin.com/hyTLLwS0

fml-server-latest.log
https://pastebin.com/Z4gSh2E3

fml-junk-earlystartup.log
https://pastebin.com/7qvBeNUd

the issue
https://ss.blamesnow.co.uk/2017/12/1512723164-b54f7d53.gif

**Comment by Exidex** [comment]
Thanks for report. Fixed in e04c811f5fda6ddba12e40895f18e3b9b01ef6dd
