### ISSUE TITLE
[1.14.4] Doesn't work

### ISSUE THREAD

**Issue by NielsPilgaard** [Exidex/SwingThroughGrass#8]
As far as I can tell `swingthroughgrass-1.14.4-1.3.2` does nothing - I am not able to swing through grass when mobs are in the grass.

Forge 1.14.4-28.1.56

**Comment by Exidex** [comment]
Checked on forge 1.14.4-28.1.61 clean install with only this mod. I am able to kill mobs through grass. Do you have more info? Maybe multimod interaction issue?

**Comment by NielsPilgaard** [comment]
Oh, my bad. I'll try to find the conflict :)

**Comment by NielsPilgaard** [comment]
Swing Through Grass works perfectly fine in Singleplayer, but I cannot get it to work on servers.

**Comment by Exidex** [comment]
well, I've checked multiplayer once again and it is working for me, so please provide more information like what exactly doesn't work, recording, logs, modlist (on client and server), etc

**Comment by NielsPilgaard** [comment]
So I found the issue - I'm not too bright. I removed it from the server weeks ago in the thought that it was client-side only. Sorry for taking your time.
